/* TP/SL Studio v3.2.0 — timeframe-safe chart selection and index-axis parsing. */
'use strict';
const $=id=>document.getElementById(id),ctx=$('chart').getContext('2d',{willReadFrequently:true}),fmt=(n,d=4)=>Number.isFinite(n)?n.toLocaleString('ro-RO',{maximumFractionDigits:d}):'—',money=n=>Number.isFinite(n)?n.toLocaleString('ro-RO',{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const state={kind:null,photos:[],active:-1,image:null,pixels:null,region:null,a:null,b:null,raw:null,bars:null,result:null,evaluation:null,reconciliation:null,statistics:null,mode:null,corner:null,rev:0,filename:'',demo:false,scanning:false};
function status(id,s,error=false){$(id).textContent=s;$(id).classList.toggle('error',error);}
function resetSizes(){const body=$('sizes');body.replaceChildren();for(const p of [2,20]){const tr=document.createElement('tr'),td=document.createElement('td'),note=document.createElement('td');td.textContent=p+'%';note.colSpan=4;note.textContent='Date insuficiente';tr.append(td,note);body.append(tr);}}
function clearReport(msg='Datele au fost schimbate. Generează din nou analiza.'){state.result=null;state.evaluation=null;state.statistics=null;$('signal').textContent='FĂRĂ SETUP';$('signal').className='';$('signalDetail').textContent=msg;['entryOut','slOut','tpOut','rrOut'].forEach(id=>$(id).textContent='—');$('tpKind').textContent='—';$('reasons').replaceChildren();$('indicators').replaceChildren();$('fibo').replaceChildren();$('activation').textContent='Nicio intrare imediată presupusă.';$('blockers').textContent='O recomandare tehnică nu este o probabilitate de profit.';$('requiredTarget').textContent='Ținta 2R se calculează separat de ținta tehnică.';$('qualityOut').textContent='—';$('qualityBar').style.width='0';$('qualityDetail').textContent='Nu este probabilitate de profit.';$('statsOut').textContent='Indisponibilă din fotografii. Importă istoric CSV suficient.';resetSizes();}
function syncActive(){const p=state.photos[state.active];if(p){p.region=state.region;p.a=state.a;p.b=state.b;p.raw=state.raw;}}
function activatePhoto(i){syncActive();const p=state.photos[i];if(!p)return;state.active=i;state.image=p.canvas;state.pixels=p.pixels;state.region=p.region||null;state.a=p.a||null;state.b=p.b||null;state.raw=p.raw||null;if(p.scan?.timeframe&&[...$('timeframe').options].some(o=>o.value===p.scan.timeframe))$('timeframe').value=p.scan.timeframe;if(state.a&&Number.isFinite(state.a.price))$('priceA').value=String(state.a.price);else $('priceA').value='';if(state.b&&Number.isFinite(state.b.price))$('priceB').value=String(state.b.price);else $('priceB').value='';renderPhotos();draw();if(state.raw){try{preview(makeBars());}catch(_){}}status('chartStatus','Fotografia '+(i+1)+' este activă'+(p.scan?.timeframe?' ('+p.scan.timeframe+')':'')+'. '+(p.raw?p.raw.length+' lumânări delimitate.':'Poți corecta manual panoul și axa.'));}
function resetSource(kind,filename=''){state.rev++;state.kind=kind;state.filename=filename;state.photos=[];state.active=-1;state.image=null;state.pixels=null;state.region=null;state.a=null;state.b=null;state.raw=null;state.bars=null;state.mode=null;state.corner=null;state.demo=kind==='demo';state.reconciliation=null;state.scanning=false;$('dataConfirmed').checked=false;$('specsConfirmed').checked=false;$('targetConfirmed').checked=false;$('target').value='';$('priceA').value='';$('priceB').value='';$('asOf').value='';for(const id of ['symbol','tick','value','spread','slippage','commission','equity','freeMargin','marginPerLot','minLot','lotStep','dailyUsed'])$(id).value='';$('timeframe').value='';$('position').value='unknown';$('event').value='unknown';$('market').value='unknown';$('dataPreview').textContent='';$('photoList').replaceChildren();$('extracted').replaceChildren();$('extractedWrap').hidden=true;$('sourceBadge').textContent=kind==='demo'?'DEMO · date sintetice':kind==='csv'?'CSV · verificare necesară':'FOTO · estimări din pixeli';clearReport();$('photoControls').hidden=kind!=='photo';draw();}
function invalidate(data=true){state.rev++;syncActive();if(data)$('dataConfirmed').checked=false;clearReport();draw();}
function draw(){const c=$('chart');if(state.image){if(c.width!==state.image.width||c.height!==state.image.height){c.width=state.image.width;c.height=state.image.height;}ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(state.image,0,0);if(state.region){ctx.save();ctx.strokeStyle='#20bed4';ctx.lineWidth=3;ctx.strokeRect(state.region.x0,state.region.y0,state.region.x1-state.region.x0,state.region.y1-state.region.y0);ctx.restore();}if(state.raw){ctx.save();state.raw.forEach((b,i)=>{ctx.strokeStyle=i===state.raw.length-1&&$('excludeLast').checked?'#ffc857':'#548cff';ctx.lineWidth=1.5;ctx.strokeRect(b.x-b.width/2-1,b.highY,b.width+2,Math.max(2,b.lowY-b.highY));});ctx.restore();}for(const [p,name,id] of [[state.a,'A','priceA'],[state.b,'B','priceB']]){if(!p)continue;ctx.save();ctx.strokeStyle=name==='A'?'#32c6e8':'#fcaf55';ctx.lineWidth=2;ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(0,p.y);ctx.lineTo(c.width,p.y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#07111e';ctx.fillRect(7,p.y-22,180,23);ctx.fillStyle=name==='A'?'#32c6e8':'#fcaf55';ctx.font='bold 14px system-ui';ctx.fillText(name+' · '+($(id).value||'preț?'),12,p.y-6);ctx.restore();}}else{c.width=900;c.height=420;ctx.fillStyle='#0b1526';ctx.fillRect(0,0,900,420);ctx.fillStyle='#8197b8';ctx.font='22px system-ui';ctx.textAlign='center';ctx.fillText('Încarcă 1–3 capturi XTB',450,204);ctx.font='15px system-ui';ctx.fillText('Grafic · ordin · detalii contract',450,238);ctx.textAlign='left';}['regionBtn','markA','markB'].forEach(id=>$(id).classList.toggle('active',state.mode===id));}
function renderPhotos(){$('photoList').replaceChildren();state.photos.forEach((p,i)=>{const box=document.createElement('div');box.className='photo-item'+(i===state.active?' active':'');const b=document.createElement('button'),img=document.createElement('img'),meta=document.createElement('div'),role=document.createElement('span');img.src=p.thumb;img.alt='Fotografia '+(i+1);b.type='button';b.setAttribute('aria-label','Deschide fotografia '+(i+1));b.append(img);b.onclick=()=>{const changed=i!==state.active;activatePhoto(i);if(changed){$('dataConfirmed').checked=false;if(p.raw)analyze();else clearReport('Fotografia selectată nu conține un grafic citit sigur.');}};meta.className='photo-meta';meta.textContent=(i+1)+'. '+p.name;role.className='photo-role';role.textContent=p.scan?.role?.length?p.scan.role.join(' + ')+(p.raw?' · '+p.raw.length+' lumânări':''):p.error?'Eroare: '+p.error:'Așteaptă citirea';meta.append(role);box.append(b,meta);$('photoList').append(box);});}
async function loadPhoto(file){const url=URL.createObjectURL(file),img=new Image();try{await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('Imaginea nu poate fi deschisă.'));img.src=url;});}finally{URL.revokeObjectURL(url);}const ratio=Math.min(1,1800/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.round(img.naturalWidth*ratio);c.height=Math.round(img.naturalHeight*ratio);const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0,c.width,c.height);return {name:file.name,canvas:c,pixels:x.getImageData(0,0,c.width,c.height),thumb:c.toDataURL('image/jpeg',.68),scan:null,region:null,a:null,b:null,raw:null,error:null};}
$('imageInput').addEventListener('change',async e=>{const files=[...e.target.files];if(!files.length)return;resetSource('photo',files.map(f=>f.name).join(', '));if(files.length>3){status('sourceStatus','Alege maximum trei fotografii din aceeași situație.',true);return;}if(files.some(f=>f.size>15*1024*1024)){status('sourceStatus','Fiecare imagine trebuie să fie sub 15 MB.',true);return;}const rev=state.rev;status('sourceStatus','Deschid '+files.length+' fotografii local…');try{const photos=await Promise.all(files.map(loadPhoto));if(rev!==state.rev)return;state.photos=photos;activatePhoto(0);status('sourceStatus',files.length+' fotografii încărcate. Apasă „Preia automat datele”.');}catch(err){if(rev===state.rev)status('sourceStatus',err.message,true);}});
$('csvInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;resetSource('csv',file.name);const rev=state.rev;try{if(file.size>8*1024*1024)throw Error('CSV prea mare (maximum 8 MB).');const bars=TP.parseCSV(await file.text());if(rev!==state.rev)return;const err=TP.validate($('excludeLast').checked?bars.slice(0,-1):bars,35);if(err)throw Error(err);state.bars=bars;status('sourceStatus',file.name+' · '+bars.length+' rânduri OHLC. Proveniența și intervalul trebuie confirmate.');preview(bars);}catch(err){if(rev===state.rev)status('sourceStatus',err.message,true);}});
$('demoBtn').onclick=()=>{resetSource('demo');state.bars=TP.demo('LONG');$('symbol').value='DEMO — fictiv';$('timeframe').value='H1';$('tick').value='0.01';$('dataConfirmed').checked=true;status('sourceStatus','DEMONSTRAȚIE: 140 lumânări sintetice. Nu sunt cotații de piață.');preview(state.bars);analyze();};
function thresholdCanvas(source){const c=document.createElement('canvas');c.width=source.width;c.height=source.height;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(source,0,0);const im=x.getImageData(0,0,c.width,c.height),d=im.data;for(let i=0;i<d.length;i+=4){const y=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2],v=y>=178?255:0;d[i]=d[i+1]=d[i+2]=v;d[i+3]=255;}x.putImageData(im,0,0);return c;}
let tesseractPromise=null;
function loadOCR(){if(window.Tesseract)return Promise.resolve(window.Tesseract);if(tesseractPromise)return tesseractPromise;tesseractPromise=new Promise((resolve,reject)=>{const s=document.createElement('script'),timer=setTimeout(()=>reject(Error('OCR nu s-a încărcat. Poți calibra manual A/B.')),30000);s.src='https://cdn.jsdelivr.net/npm/tesseract.js@6.0.1/dist/tesseract.min.js';s.onload=()=>{clearTimeout(timer);window.Tesseract?resolve(window.Tesseract):reject(Error('OCR indisponibil.'));};s.onerror=()=>{clearTimeout(timer);reject(Error('Rețeaua a blocat OCR. Completează manual.'));};document.head.append(s);}).catch(e=>{tesseractPromise=null;throw e;});return tesseractPromise;}
async function scanAll(){if(!state.photos.length){status('sourceStatus','Adaugă mai întâi 1–3 fotografii.',true);return;}if(state.scanning)return;state.scanning=true;$('scanAllBtn').disabled=true;$('ocrBtn').disabled=true;const token=++state.rev;let worker;
 try{const T=await loadOCR();if(token!==state.rev)return;worker=await T.createWorker('eng',1,{logger:m=>{if(token===state.rev&&m.status==='recognizing text')status('sourceStatus','Citire locală OCR: '+Math.round(m.progress*100)+'%…');}});
  for(let i=0;i<state.photos.length;i++){if(token!==state.rev)return;const p=state.photos[i];status('sourceStatus','Fotografia '+(i+1)+'/'+state.photos.length+': text și prețuri…');try{
   await worker.setParameters({tessedit_pageseg_mode:'11'});const original=await worker.recognize(p.canvas,{}, {blocks:true});
   await worker.setParameters({tessedit_pageseg_mode:'6'});const contrast=await worker.recognize(thresholdCanvas(p.canvas),{}, {blocks:false});
   p.scan=Vision.parseXtb((original.data.text||'')+'\n'+(contrast.data.text||''));p.ocrWords=Vision.words(original.data);
   try{p.axis=Vision.findAxis(p.ocrWords,p.canvas.width,p.canvas.height,$('scale').value==='log',p.scan?.symbol);p.region=Vision.inferRegion(p.axis,p.canvas.width,p.canvas.height);p.a={y:p.axis.a.y,price:p.axis.a.price};p.b={y:p.axis.b.y,price:p.axis.b.price};p.raw=Vision.detect(p.pixels,p.region).candles;}catch(err){p.chartError=err.message;}
  }catch(err){p.error=err.message;}renderPhotos();}
  if(token!==state.rev)return;state.reconciliation=Vision.reconcile(state.photos.map(p=>p.scan).filter(Boolean),{localOffsetMinutes:-new Date().getTimezoneOffset()});renderExtracted(state.reconciliation);applyExtracted(state.reconciliation);
  const wanted=state.reconciliation.fields.timeframe?.value,chosen=Vision.chooseChart(state.photos,wanted);state.active=-1;if(chosen>=0){activatePhoto(chosen);preview(makeBars());const p=state.photos[chosen],multi=state.reconciliation.fields.timeframe?.multiple;status('chartStatus','Am ales automat fotografia '+(chosen+1)+' cu '+p.raw.length+' lumânări '+(p.scan?.timeframe||'')+(multi?' — intervalul de execuție cel mai scurt detectat; celelalte intervale rămân context.':'.')+' Verifică marcajele și scara A/B.');analyze();}else{activatePhoto(0);status('chartStatus','Textul a fost extras, dar graficul nu a fost citit sigur. Selectează manual panoul și A/B sau folosește CSV.',true);}
  status('sourceStatus','Citirea celor '+state.photos.length+' fotografii s-a încheiat. Verifică valorile înainte de utilizare.');
 }catch(err){if(token===state.rev)status('sourceStatus',err.message,true);}finally{if(worker)await worker.terminate().catch(()=>{});state.scanning=false;$('scanAllBtn').disabled=false;$('ocrBtn').disabled=false;draw();}
}
$('scanAllBtn').onclick=scanAll;$('ocrBtn').onclick=scanAll;
function addExtractedRow(label,value,note,state=''){const tr=document.createElement('tr'),a=document.createElement('td'),b=document.createElement('td'),c=document.createElement('td');a.textContent=label;b.textContent=value;c.textContent=note;if(state)c.className=state;tr.append(a,b,c);$('extracted').append(tr);}
function renderExtracted(r){$('extracted').replaceChildren();$('extractedWrap').hidden=false;const labels={symbol:['Instrument',''],timeframe:['Interval',''],current:['Preț afișat',' USD'],sell:['SELL / bid',' USD'],buy:['BUY / ask',' USD'],volume:['Volum selectat',' lot'],marginRon:['Marjă la volumul selectat',' RON'],freeMarginRon:['Fonduri libere',' RON'],spreadRon:['Spread monetar',' RON'],spreadPrice:['Spread preț',''],commissionRon:['Comision afișat',' RON'],contractUsd:['Valoare contract',' USD'],contractRon:['Valoare contract',' RON'],swapSellRon:['Swap zilnic SELL',' RON'],swapBuyRon:['Swap zilnic BUY',' RON'],pipValueRon:['Valoare pip la volumul selectat',' RON'],market:['Piață','']};for(const [key,[label,unit]] of Object.entries(labels)){const x=r.fields[key];if(!x)continue;let val=typeof x.value==='number'?fmt(x.value,8)+unit:String(x.value),note=x.multiple?'intervale intenționate: '+x.values.join(' + '):'fotografiile '+x.sources.join(', ');if(Number.isFinite(x.min)&&x.max>x.min)note+=' · observat '+fmt(x.min,8)+'–'+fmt(x.max,8)+unit;if(x.source)note+=' · folosită fotografia '+x.source+' (cea mai recentă)';if(x.moving)note+=' · mișcare normală între capturi';if(x.conflict)note+=' · NECONCORDANȚĂ';addExtractedRow(label,val,note,x.conflict?'conflict':x.moving||x.multiple?'moving':'');}
 if(r.derived.times?.length)addExtractedRow('Ore normalizate',r.derived.times.map(x=>'foto '+x.source+': '+x.localValue).join(' · '),r.derived.times.some(x=>x.converted)?'orele UTC de pe grafic au fost convertite la fusul dispozitivului':'ore locale OCR');
 if(Number.isFinite(r.derived.valuePerLot))addExtractedRow('Valoare calculată / lot',fmt(r.derived.valuePerLot,2)+' RON / 1,00 mișcare','valoare pip ÷ volum; necesită verificare');
 if(Number.isFinite(r.derived.marginPerLot))addExtractedRow('Marjă calculată / lot',money(r.derived.marginPerLot)+' RON','marjă afișată ÷ volum; necesită verificare');
 if(r.derived.equityEstimate)addExtractedRow('Equity dedus condiționat',money(r.derived.equityEstimate.min)+(r.derived.equityEstimate.max>r.derived.equityEstimate.min?'–'+money(r.derived.equityEstimate.max):'')+' RON','fonduri libere + marjă; NU este folosit automat');
 if(r.fields.positionVolume)addExtractedRow('Poziție detectată',r.fields.positionVolume.value+' lot'+(r.derived.position?' · '+r.derived.position:''),'confirmă în Portofoliu; nivelul din grafic poate fi ambiguu','conflict');
 const names={symbol:'instrumente diferite',market:'stări diferite ale pieței',spreadPrice:'spreaduri incompatibile',volume:'volume diferite',current:'preț principal incompatibil'},missing=['equity afișat direct','volum minim și pas','slippage','calendar de știri','confirmarea pozițiilor totale'],movement=r.fields.current?.moving||r.fields.sell?.moving||r.fields.buy?.moving;let lead=r.severe.length?'Există neconcordanțe importante: '+r.severe.map(x=>names[x]||x).join(', ')+'. ':movement?'Piața era deschisă; variațiile dintre capturi au fost tratate ca mișcare de piață, nu ca eroare. ':'Valorile repetate sunt coerente.';if(r.warnings?.length)lead+=' Verificări: '+[...new Set(r.warnings)].join(' ');status('reconcileStatus',lead+' Scor extracție '+r.score+'/100 (nu probabilitate). Lipsesc: '+missing.join(', ')+'.',r.severe.length>0);}
function applyExtracted(r){const f=r.fields,d=r.derived;if(f.symbol&&!$('symbol').value)$('symbol').value=f.symbol.value;if(f.timeframe)$('timeframe').value=f.timeframe.value;if(f.spreadPrice)$('spread').value=String(f.spreadPrice.value);if(f.commissionRon?.value===0)$('commission').value='0';if(f.freeMarginRon)$('freeMargin').value=String(f.freeMarginRon.value);if(Number.isFinite(d.marginPerLot))$('marginPerLot').value=String(d.marginPerLot);if(Number.isFinite(d.valuePerLot))$('value').value=String(d.valuePerLot);if(Number.isFinite(d.tickSuggested)&&!$('tick').value)$('tick').value=String(d.tickSuggested);if(f.market)$('market').value=f.market.value;if(d.position)$('position').value='yes';$('specsConfirmed').checked=false;$('dataConfirmed').checked=false;}
function setMode(id){if(!state.image){status('chartStatus','Încarcă mai întâi o poză.',true);return;}state.mode=id;state.corner=null;status('chartStatus',id==='regionBtn'?'Atinge colțul stânga-sus al panoului de preț.':'Atinge înălțimea unui preț de pe axă, apoi introdu valoarea pentru '+(id==='markA'?'A.':'B.'));draw();}
$('regionBtn').onclick=()=>setMode('regionBtn');$('markA').onclick=()=>setMode('markA');$('markB').onclick=()=>setMode('markB');
$('chart').addEventListener('click',e=>{if(!state.image||!state.mode)return;const rect=$('chart').getBoundingClientRect(),p={x:(e.clientX-rect.left)*$('chart').width/rect.width,y:(e.clientY-rect.top)*$('chart').height/rect.height};if(state.mode==='regionBtn'){if(!state.corner){state.corner=p;status('chartStatus','Acum atinge colțul dreapta-jos, înaintea cifrelor axei.');return;}const a=state.corner;state.region={x0:Math.min(a.x,p.x),x1:Math.max(a.x,p.x),y0:Math.min(a.y,p.y),y1:Math.max(a.y,p.y)};state.raw=null;state.corner=null;status('chartStatus','Panou selectat. Citește axa sau indică A și B.');}else{const isA=state.mode==='markA';state[isA?'a':'b']={y:p.y};$(isA?'priceA':'priceB').focus();status('chartStatus','Reper marcat. Introdu prețul afișat la această înălțime.');}state.mode=null;invalidate();});
$('clearBtn').onclick=()=>{state.region=null;state.a=null;state.b=null;state.raw=null;$('priceA').value='';$('priceB').value='';invalidate();status('chartStatus','Selectează din nou panoul și reperele A/B.');};
function makeBars(){if(state.kind!=='photo')return state.bars;const a=state.a&&{y:state.a.y,price:TP.num($('priceA').value)},b=state.b&&{y:state.b.y,price:TP.num($('priceB').value)};return TP.calibrate(state.raw||[],a,b,$('scale').value==='log');}
function preview(bars){const b=bars.at(-1);$('dataPreview').textContent=bars.length+' lumânări · ultima extrasă: O '+fmt(b.open)+' / H '+fmt(b.high)+' / L '+fmt(b.low)+' / C '+fmt(b.close)+'. '+(state.kind==='photo'?'Estimare din pixeli; compară cu platforma.':'Verifică ordinea cronologică.');}
$('detectBtn').onclick=()=>{try{if(!state.image||!state.region)throw Error('Încarcă poza și selectează panoul cu lumânări.');TP.mapPrice(state.region.y0,state.a&&{y:state.a.y,price:TP.num($('priceA').value)},state.b&&{y:state.b.y,price:TP.num($('priceB').value)},$('scale').value==='log');invalidate();const found=Vision.detect(state.pixels,state.region);state.raw=found.candles;syncActive();preview(makeBars());status('chartStatus','Am delimitat '+found.count+' lumânări. Albastru = extrase; galben = ultima exclusă. '+found.warnings.join(' '));draw();}catch(err){state.raw=null;syncActive();clearReport();status('chartStatus',err.message,true);}};
function getCosts(){const o={priceBasis:'reference'};['value','spread','slippage','commission','equity','freeMargin','marginPerLot','minLot','lotStep','dailyUsed'].forEach(k=>o[k]=TP.num($(k).value));return o;}
function selectedTarget(p){if($('target').value.trim())return {value:TP.num($('target').value),kind:$('targetConfirmed').checked?'Nivel introdus și confirmat':'Nivel introdus · neconfirmat',confirmed:$('targetConfirmed').checked};if(p.tp!==null)return {value:p.tp,kind:'Pivot istoric observat',confirmed:true};const v=p.projection1618;return {value:v>0?v:null,kind:'Proiecție Fibonacci 161,8% · neconfirmată',confirmed:false};}
function evidenceQuality(r,target){let q=r.quality||0;if(state.kind==='photo')q-=12;if(!$('dataConfirmed').checked)q-=15;if(!target?.confirmed)q-=8;if(!$('asOf').value&&!state.demo)q-=5;if(state.reconciliation)q=q*.78+state.reconciliation.score*.22;if(state.reconciliation?.severe.length)q-=15;return Math.max(0,Math.min(100,Math.round(q)));}
function renderStats(r){let s=null;if(state.kind==='csv'&&state.bars?.length>=1200&&['LONG','SHORT'].includes(r.direction))s=TP.backtest(state.bars,{tick:TP.num($('tick').value),direction:r.direction,horizon:12});state.statistics=s;if(!s){$('statsOut').textContent='Neestimabilă din fotografii sau dintr-un istoric prea scurt. Sunt necesare minimum 1.200 bare CSV.';return;}if(!s.trades){$('statsOut').textContent=s.reason;return;}const wrap=document.createElement('div');wrap.className='stats-grid';for(const [label,val] of [['TP înainte de SL',fmt(s.hitRate*100,1)+'%'],['SL înainte de TP',fmt(s.lossRate*100,1)+'%'],['Expirare la 12 bare',fmt(s.expiryRate*100,1)+'%'],['Activare semnal',fmt(s.activationRate*100,1)+'%'],['Rezultat mediu',fmt(s.meanR,2)+'R'],['Profit factor',Number.isFinite(s.profitFactor)?fmt(s.profitFactor,2):'—'],['Drawdown maxim',fmt(s.maxDrawdownR,2)+'R'],['Cazuri activate',String(s.trades)],['Interval Wilson 95%',s.interval?fmt(s.interval.low*100,1)+'–'+fmt(s.interval.high*100,1)+'%':'—'],['Variație pe trimestre',s.stabilityRange?fmt(s.stabilityRange.low*100,1)+'–'+fmt(s.stabilityRange.high*100,1)+'%':'eșantion mic']]){const d=document.createElement('div'),b=document.createElement('b'),x=document.createElement('span');b.textContent=val;x.textContent=label;d.append(b,x);wrap.append(d);}$('statsOut').replaceChildren(wrap,document.createTextNode(s.reason+' Folosește exact același instrument, interval și tip de contract; costurile istorice nu sunt incluse. '+(s.sufficient?'Eșantion minim atins.':'Eșantion insuficient: nu trata rata ca probabilitate utilizabilă.')));}
function analyze(){clearReport();try{if(!$('symbol').value.trim()||!$('timeframe').value)throw Error('Completează instrumentul și intervalul lumânărilor.');const bars=makeBars();if(!bars||!bars.length)throw Error('Încarcă CSV sau extrage lumânările din fotografii.');const result=TP.analyze(bars,{excludeLast:$('excludeLast').checked,tick:TP.num($('tick').value)});state.result=result;render();status('actionStatus',$('dataConfirmed').checked?'Analiză recalculată din date confirmate de utilizator.':'Propunere preliminară generată; datele extrase nu sunt încă confirmate.');}catch(err){clearReport(err.message);status('actionStatus',err.message,true);}}
$('analyzeBtn').onclick=analyze;
function render(){const r=state.result;if(!r)return;state.evaluation=null;resetSizes();$('rrOut').textContent='—';$('signal').textContent=r.direction==='LONG'?'BUY LONG condiționat':r.direction==='SHORT'?'SELL SHORT condiționat':'FĂRĂ SETUP';$('signal').className=r.direction==='LONG'?'long':r.direction==='SHORT'?'short':'';$('sourceBadge').textContent=state.demo?'DEMO · NU TRANZACȚIONA':state.kind==='photo'?'1–3 FOTO · aproximativ':'CSV · sursă importată';$('signalDetail').textContent=$('symbol').value+' · '+$('timeframe').value+' · '+r.bars.length+' lumânări închise · '+(state.demo?'exemplu sintetic':$('asOf').value?'data sursei: '+$('asOf').value.replace('T',' '):'data sursei neconfirmată');$('reasons').replaceChildren();r.reasons.forEach(s=>{const li=document.createElement('li');li.textContent=s;$('reasons').append(li);});$('indicators').replaceChildren();if(r.ind)for(const [key,name] of [['ema20','EMA20'],['ema50','EMA50'],['atr14','ATR14'],['rsi14','RSI14'],['macd','MACD'],['macdSignal','Semnal MACD']]){const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=fmt(r.ind[key]);div.append(dt,dd);$('indicators').append(div);}renderStats(r);if(!r.plan){$('blockers').textContent=(r.error||'DE URMĂRIT. '+r.reasons.join(' '))+' Probabilitatea de profit este neestimabilă.';$('qualityOut').textContent=fmt(r.quality,0)+'/100';$('qualityBar').style.width=(r.quality||0)+'%';$('qualityDetail').textContent='Scor diagnostic al dovezilor, nu probabilitate.';return;}
 const p=r.plan,target=selectedTarget(p),q=evidenceQuality(r,target);$('qualityOut').textContent=q+'/100';$('qualityBar').style.width=q+'%';$('qualityDetail').textContent='Scor de calitate al structurii, datelor și țintei; nu probabilitate.';$('entryOut').textContent=fmt(p.entry,8);$('slOut').textContent=fmt(p.sl,8);$('tpOut').textContent=fmt(target.value,8);$('tpKind').textContent=target.kind;const side=r.direction==='LONG'?'peste':'sub';$('activation').textContent='Așteaptă o lumânare închisă '+side+' '+fmt(p.trigger)+', apoi un retest menținut. Intrare de referință '+fmt(p.entry)+'. Recalculează dacă prețul executabil diferă. SL '+fmt(p.sl)+'; tampon '+fmt(p.pad)+' (maxim dintre 2 ticks și 0,25 ATR).';
 const blocks=[];if(state.demo)blocks.push('Exemplu sintetic.');if(!$('dataConfirmed').checked)blocks.push('Datele/OCR nu sunt confirmate de utilizator.');if(!target.confirmed)blocks.push('TP este proiecție sau nivel neconfirmat.');if(state.kind==='photo')blocks.push('OHLC și indicatorii sunt estimări din pixeli.');if(!$('asOf').value&&!state.demo)blocks.push('Data sursei nu este confirmată.');if(state.reconciliation?.severe.length)blocks.push('Există neconcordanțe între capturi.');if($('position').value!=='no')blocks.push('Poziție existentă sau statut necunoscut: fără CFD nou.');if($('event').value!=='no')blocks.push('Calendar/eveniment major neverificat ori activ.');if($('market').value!=='open')blocks.push('Piața/produsul nu sunt confirmate disponibile.');if(!$('specsConfirmed').checked)blocks.push('Costurile și specificațiile nu sunt confirmate.');
 const costs=getCosts();costs.target=target.value;const ev=TP.evaluate(p,r.direction,costs);if(ev.error)blocks.push(ev.error);else{if(!$('specsConfirmed').checked)blocks.push('Lotaj necalculat până la confirmarea specificațiilor.');else{state.evaluation=ev;const body=$('sizes');body.replaceChildren();ev.sizes.forEach(s=>{const tr=document.createElement('tr');[s.pct+'%',fmt(s.lots,8),money(s.loss),money(s.profit),money(s.margin)].forEach(t=>{const td=document.createElement('td');td.textContent=t;tr.append(td);});body.append(tr);});}$('rrOut').textContent=Number.isFinite(ev.rr)?fmt(ev.rr,2)+' : 1':'—';if(ev.rr===null||ev.rr<2)blocks.push('Raportul recompensă/risc net nu atinge 2:1.');$('requiredTarget').textContent='Pentru 2R net ar fi necesar '+fmt(ev.requiredTP,8)+'. Este prag aritmetic, nu țintă tehnică. Distanță SL '+fmt(ev.riskDistance)+'; distanță TP '+fmt(ev.rewardDistance)+'; cost '+fmt(ev.costPrice)+' unități de preț.';}
 $('blockers').textContent='DE URMĂRIT · '+blocks.join(' ')+' Niciun ordin este transmis; volum de execuție 0.';$('fibo').replaceChildren();const intro=document.createElement('p');intro.className='hint';intro.textContent='Extreme: low '+fmt(p.swingLow)+' / high '+fmt(p.swingHigh)+'. Retrageri de la '+(r.direction==='LONG'?'maxim în jos.':'minim în sus.');$('fibo').append(intro);const table=document.createElement('table');p.fib.forEach(v=>{const tr=document.createElement('tr'),a=document.createElement('td'),b=document.createElement('td');a.textContent=fmt(v.percent,1)+'%';b.textContent=fmt(v.price);tr.append(a,b);table.append(tr);});$('fibo').append(table);
}
$('costBtn').onclick=()=>{if(!state.result){status('actionStatus','Generează întâi analiza tehnică.',true);return;}render();status('actionStatus','Costurile și simularea au fost actualizate.');};
['priceA','priceB','tick','symbol','asOf'].forEach(id=>$(id).addEventListener('input',()=>invalidate()));['scale','timeframe','excludeLast'].forEach(id=>$(id).addEventListener('change',()=>invalidate()));$('dataConfirmed').addEventListener('change',()=>{state.rev++;clearReport();});['value','spread','slippage','commission','equity','freeMargin','marginPerLot','minLot','lotStep','dailyUsed'].forEach(id=>$(id).addEventListener('input',()=>{$('specsConfirmed').checked=false;if(state.result)render();}));['position','event','market','specsConfirmed','targetConfirmed'].forEach(id=>$(id).addEventListener('change',()=>{if(state.result)render();}));$('target').addEventListener('input',()=>{$('targetConfirmed').checked=false;if(state.result)render();});
$('exportBtn').onclick=()=>{if(!state.result){status('actionStatus','Nu există analiză de exportat.',true);return;}const scans=state.photos.map((p,i)=>p.scan?{photo:i+1,name:p.name,...Object.fromEntries(Object.entries(p.scan).filter(([k])=>k!=='raw'))}:null).filter(Boolean),payload={version:'3.2.0',exportedAt:new Date().toISOString(),symbol:$('symbol').value,timeframe:$('timeframe').value,source:{kind:state.kind,filenames:state.photos.map(p=>p.name),activePhoto:state.active+1,asOf:$('asOf').value||null,synthetic:state.demo,approximate:state.kind==='photo',confirmed:$('dataConfirmed').checked,excludeLast:$('excludeLast').checked,scale:$('scale').value,ocr:scans,reconciliation:state.reconciliation,calibration:state.kind==='photo'?{a:state.a&&{...state.a,price:TP.num($('priceA').value)},b:state.b&&{...state.b,price:TP.num($('priceB').value)}}:null},analysis:state.result,statistics:state.statistics,target:state.result.plan?selectedTarget(state.result.plan):null,costs:getCosts(),simulation:state.evaluation,checks:{specs:$('specsConfirmed').checked,position:$('position').value,market:$('market').value,event:$('event').value},executionVolume:0,probability:state.statistics?.sufficient?{kind:'rată empirică istorică TP-înainte-de-SL; nu probabilitate calibrată pentru următoarea tranzacție',estimate:state.statistics.hitRate,interval95:state.statistics.interval}:null,ordersSent:false};const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download='analiza-tp-sl.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('actionStatus','Analiza a fost exportată local, fără fotografii și fără textul OCR brut.');};$('printBtn').onclick=()=>window.print();draw();
